### ISSUE TITLE
集成go-micro报错

### ISSUE THREAD

**Issue by soooldier** [SkyAPM/go2sky#110]
**Describe the bug**
go-micro集成报错：
 code = Unimplemented desc = Method not found: skywalking.v3.ManagementService/reportInstanceProperties

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1681065/118975511-a80bfe00-b9a6-11eb-997e-9c244f5c58a6.png)
![image](https://user-images.githubusercontent.com/1681065/118975649-d093f800-b9a6-11eb-973e-118c48e0be1e.png)

**Desktop (please complete the following information):**
 - OS: [e.g. MAC]
 - OAP版本: [8.3.0-es6]

**Additional context**

**Comment by kezhenxu94** [comment]
go2sky 1.0.0 only supports OAP 8.6.0, which is not yet released, for older OAP, you need to use go2skyw 0.6.0
