### ISSUE TITLE
grpc 无法连接

### ISSUE THREAD

**Issue by songning4** [SkyAPM/go2sky#116]
为了兼容etcd使用了grpc1.26.0，所以将go2sky也降到了0.6.0，虽然可以启动，但是启动后会报错：

go2sky-gRPC2021/06/03 17:53:33 open stream error rpc error: code = Canceled desc = grpc: the client connection is closing
go2sky-gRPC2021/06/03 17:53:38 open stream error rpc error: code = Canceled desc = grpc: the client connection is closing
go2sky-gRPC2021/06/03 17:53:43 open stream error rpc error: code = Canceled desc = grpc: the client connection is closing
go2sky-gRPC2021/06/03 17:53:48 open stream error rpc error: code = Canceled desc = grpc: the client connection is closing
go2sky-gRPC2021/06/03 17:53:53 open stream error rpc error: code = Canceled desc = grpc: the client connection is closing

服务端也没有收到任何数据，请问下怎么处理😰谢谢

**Comment by wu-sheng** [comment]
This means you closed the reporter. Not go2sky's issue.

**Comment by lppgo** [comment]
你好。请问你这边解决了吗

**Comment by lppgo** [comment]
我发现了，是本地的proxy代理导致的

**Comment by lppgo** [comment]
我这边是没有任何报错信息，但在skywalking ui看不到任何数据，可以请教一下吗。我的邮箱1605577372@qq.com
