### ISSUE TITLE
如何上报related logs

### ISSUE THREAD

**Issue by soooldier** [SkyAPM/go2sky#117]
请问skywalking UI 里的related logs是什么功能呢？需要如何上报log数据？
![image](https://user-images.githubusercontent.com/1681065/120631969-0eab1480-c49b-11eb-8d55-b0b9c5846dcf.png)

**Comment by wu-sheng** [comment]
Check latest SkyWalking branch, and latest go2sky.
Trace context is injected by go2sky. And use filebeat or fluentd to collect logs to OAP https://skywalking.apache.org/docs/main/latest/en/setup/backend/log-analyzer/
At last, use LAL to build the links. https://skywalking.apache.org/docs/main/latest/en/concepts-and-designs/lal/
