### ISSUE TITLE
异步数据上报展示错误

### ISSUE THREAD

**Issue by soooldier** [SkyAPM/go2sky#118]
**Describe the bug**
调用代码大概如下
```go
span1, _, _ := tracer.CreateLocalSpan(ctx, go2sky.WithOperationName("同步操作"))
// 异步操作，应用程序不需拿到结果
go func() {
    time.Sleep(3 * time.Second)
    span2, _, _ :=tracer.CreateLocalSpan(ctx, go2sky.WithOperationName("异步操作"))
    span2.End()
}()
span1.End()
```

SkyWalking UI展示效果：

![image](https://user-images.githubusercontent.com/1681065/123225399-45f26b80-d505-11eb-9b52-3cf9b474c6ee.png)

期望展示效果：

![image](https://user-images.githubusercontent.com/1681065/123225665-8356f900-d505-11eb-8dda-78e5a796660c.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by wu-sheng** [comment]
This is not a bug. This is about when and how you use `ctx`.

**Comment by soooldier** [comment]
不好意思请教一下，针对示例中的场景应该怎样使用ctx才是最佳实践呢？

**Comment by haishenming** [comment]
遇到一样的问题，同问，最佳实践。。。
