### ISSUE TITLE
golang项目-go2sky-client-0.6 接入skywalking8.6 ：每秒1w+ 日志输出 reach max send buffer

### ISSUE THREAD

**Issue by yyt701** [SkyAPM/go2sky#121]
请教：

golang项目-go2sky-client-0.6 接入skywalking8.6 ：

go业务系统日志 每秒1w+ 日志输出：go2sky-gRPC2021/06/22 21:35:34 reach max send buffer

1. 这是gosky客户端版本问题 还是 grpc版本不匹配原因？
2. 使用上是否有参数需要进行设置、调优？
3. 还是其他使用方面的原因？ skywalking+es 集群 处理数据上报不够及时

多谢大佬，赐教

**Comment by wu-sheng** [comment]
Duplicate https://github.com/SkyAPM/go2sky/issues/120. I am not sure do you all people in a group or somehow ask for the same thing.

**Comment by yyt701** [comment]
You function is to close issues without saying anything
