### ISSUE TITLE
Reporter fails to report spans finished near the program ending

### ISSUE THREAD

**Issue by yaojingguo** [SkyAPM/go2sky#123]
**Describe the bug**
 Go program exits before finished spans are reported.

**To Reproduce**

Run the following code:
```
	re, err := reporter.NewLogReporter()
	if err != nil {
		log.Fatalf("new reporter error: %v", err)
	}
	defer re.Close()

	tracer, err := go2sky.NewTracer("test", go2sky.WithReporter(re))
	if err != nil {
		log.Fatalf("create tracer error: %v", err)
	}

	ctx := context.Background()
	span, _, _ := tracer.CreateLocalSpan(ctx, go2sky.WithOperationName("second"))
	span.End()
```

logReporter does not log the finished span.

If `time.Sleep(1 * time.Second)` is added to the bottom of the code, the span is logged:

```
go2sky-log2021/08/03 20:20:54 Segment-3fe80942f45511ebadd38c85901e7895: [{"Refs":null,"StartTime":"2021-08-03T20:20:54.650076+08:00","EndTime":"2021-08-03T20:20:54.6501+08:00","OperationName":"second","Peer":"","Layer":0,"ComponentID":0,"Tags":null,"Logs":null,"IsError":false,"SpanType":2,"TraceID":"3fe808d4f45511ebadd38c85901e7895","SegmentID":"3fe80942f45511ebadd38c85901e7895","SpanID":0,"ParentSpanID":-1,"ParentSegmentID":"","CorrelationContext":{}}]
```
gRPCReporter  has the same problem.

**Comment by yaojingguo** [comment]
I suggest adding a mechanism to wait for finished spans to be reported with a timeout. I have already done some coding to do it. I will submit a patch soon.

**Comment by wu-sheng** [comment]
> Go program exits before finished spans are reported.

Typically, there is no such mechanism in any SDK/agent, including SkyWalking Java agent. We don't block the client-side exiting process.

**Comment by yaojingguo** [comment]
Can we make an option for such a mechanism? 

At least, we should document the case for such span reporting failures. Otherwise, it will confuse new users.

**Comment by wu-sheng** [comment]
> Can we make an option for such a mechanism?
> 
> At least, we should document the case for such span reporting failures. Otherwise, it will confuse new users.

The document, yes, if you want to contribute. A new mechanism, I am not sure. That depends on how.
But after all, this is not on the core team agenda.
