### ISSUE TITLE
Span context is needed after CreateExitSpan

### ISSUE THREAD

**Issue by kagaya85** [SkyAPM/go2sky#125]
In some scenarios (such as in middleware chain)，span context is needed after doing `CreateExitSpan`, but the `CreateExitSpan` method won't return the context that include span info right now, even can't get span info from a span object

For the solution, IMHO, we can change the `CreateExitSpan` to return this context directly like what `CreateEntrySpan` & `CreateLocalSpan` do, but this may make a BC:

```go
// New CreateExitSpan
func (t *Tracer) CreateExitSpan(ctx context.Context, operationName string, peer string, injector propagation.Injector) (Span, context.Context, error)
```

Another choice I considered is to expand the `Span` interface methods, add new methods like `SpanID`, `TraceID`, `Context`, etc.

```go
// Context will return a context includes current span
func (ds *defaultSpan) Context(ctx context.Context) context.Context {
	return context.WithValue(ctx, ctxKeyInstance, *ds)
}
```

we can create a new methods collection interface with the current `Span` interface embedded, just assert to new interface when using new methods

Please give me some advice, thanks in advance :)

**Comment by wu-sheng** [comment]
I think both works, but we need to keep API forward compatbility.
Does option 1 break nothing?

**Comment by kagaya85** [comment]
> Does option 1 break nothing?

It returns a new value `context.Context`, the numbers of return value change from 2 to 3

**Comment by arugal** [comment]
>  but we need to keep API forward compatbility.

I'm leaning toward option 2, and we can also add a `CreateExitSpanWithContext` func.

Like this: 
```go
func (t *Tracer) CreateExitSpanWithContext(ctx context.Context, operationName string, peer string, injector propagation.Injector) (Span, context.Context, error)

```

**Comment by wu-sheng** [comment]
We should not break API, as we are at 1.x stable iteration stage.
I agree with @arzhan, a new API makes more sense. CreateExitSpanWithContext is preferred by me.

**Comment by kagaya85** [comment]
Okay, I'll get to work on it.
