### ISSUE TITLE
use jmeter to test go2sky performance, error like this

### ISSUE THREAD

**Issue by lokichoggio** [SkyAPM/go2sky#127]
go2sky-gRPC2021/09/14 03:07:36 send segment error EOF
go2sky-gRPC2021/09/14 03:07:36 send closing error rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR
go2sky-gRPC2021/09/14 03:07:42 send segment error EOF
go2sky-gRPC2021/09/14 03:07:42 send closing error rpc error: code = Unknown desc = unexpected HTTP status code received from server: 413 (Request Entity Too Large); transport: received unexpected content-type "text/html"
go2sky-gRPC2021/09/14 03:07:44 send segment error EOF
go2sky-gRPC2021/09/14 03:07:44 send closing error rpc error: code = Unknown desc = unexpected HTTP status code received from server: 413 (Request Entity Too Large); transport: received unexpected content-type "text/html"
go2sky-gRPC2021/09/14 03:07:46 send segment error EOF
go2sky-gRPC2021/09/14 03:07:46 send closing error rpc error: code = Unknown desc = unexpected HTTP status code received from server: 413 (Request Entity Too Large); transport: received unexpected content-type "text/html"
go2sky-gRPC2021/09/14 03:07:48 send segment error EOF
go2sky-gRPC2021/09/14 03:07:48 send closing error rpc error: code = Unknown desc = unexpected HTTP status code received from server: 413 (Request Entity Too Large); transport: received unexpected content-type "text/html"
go2sky-gRPC2021/09/14 03:07:50 send segment error EOF
go2sky-gRPC2021/09/14 03:07:50 send closing error rpc error: code = Unknown desc = unexpected HTTP status code received from server: 413 (Request Entity Too Large); transport: received unexpected content-type "text/html"
go2sky-gRPC2021/09/14 03:07:52 send segment error EOF
go2sky-gRPC2021/09/14 03:07:52 send closing error rpc error: code = Unknown desc = unexpected HTTP status code received from server: 413 (Request Entity Too Large); transport: received unexpected content-type "text/html"
go2sky-gRPC2021/09/14 03:07:54 send segment error EOF
go2sky-gRPC2021/09/14 03:07:54 send closing error rpc error: code = Unknown desc = unexpected HTTP status code received from server: 413 (Request Entity Too Large); transport: received unexpected content-type "text/html"
go2sky-gRPC2021/09/14 03:07:57 send segment error EOF
go2sky-gRPC2021/09/14 03:07:57 send closing error rpc error: code = Unknown desc = unexpected HTTP status code received from server: 413 (Request Entity Too Large); transport: received unexpected content-type "text/html"

**Comment by wu-sheng** [comment]
This seems like your OAP server doesn't have enough resources to support the traffic. Maybe because of storage, cluster size, etc.
