### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by niyanchun** [SkyAPM/go2sky#133]
I install the repo following the README:

![image](https://user-images.githubusercontent.com/5145759/136518630-569d1961-5917-42df-b635-36ef477af8b1.png)

but get following error:

```
-> % go get -u github.com/SkyAPM/go2sky
package skywalking.apache.org/repo/goapi/collect/common/v3: unrecognized import path "skywalking.apache.org/repo/goapi/collect/common/v3": reading https://skywalking.apache.org/repo/goapi/collect/common/v3?go-get=1: 404 Not Found
package skywalking.apache.org/repo/goapi/collect/language/agent/v3: unrecognized import path "skywalking.apache.org/repo/goapi/collect/language/agent/v3": reading https://skywalking.apache.org/repo/goapi/collect/language/agent/v3?go-get=1: 404 Not Found
````

it seems some package has moved to other place?

**Comment by wu-sheng** [comment]
This seems correct path. CI is using this.

**Comment by niyanchun** [comment]
It's so weird, I doubt there's something wrong with my network or go config. But it's normal when  I installed other golang repos in github.com. Only Go2Sky not work... On the other hand, although go get got some error promt, I found go2sky module has been download in my $GOPATH/src/github.com/SkyAPM/go2sky.

**Comment by wu-sheng** [comment]
We use skywalking.org as hosted domain, but target to github

**Comment by showsmall** [comment]
@niyanchun How did you solve it in the end? I also encountered this problem

**Comment by wu-sheng** [comment]
This is typically caused by China's local network issue. Sometimes require VPN, but some have to disable VPN.
