### ISSUE TITLE
How to send log to the log page?

### ISSUE THREAD

**Issue by mmooyyii** [SkyAPM/go2sky#137]
here is skywalking's log page, I can find any log
![image](https://user-images.githubusercontent.com/25590607/142985724-19f4e411-a51b-4b39-b192-fe27d3add406.png)

here is my code
``` go

package main
import (
	"context"
	"fmt"
	"github.com/SkyAPM/go2sky"
	"github.com/SkyAPM/go2sky/reporter"
	"time"
)

func main() {
	r, err := reporter.NewGRPCReporter("172.16.0.127:11800")
	if err != nil {
		return
	}
	tracer, err := go2sky.NewTracer("example", go2sky.WithReporter(r))
	span, _, err := tracer.CreateLocalSpan(context.Background())
	if err != nil {
		return
	}
	time.Sleep(time.Millisecond * 100)
	span.SetOperationName("log")
	span.Log(time.Now(), "123")
	span.End()
	time.Sleep(time.Second * 2)
	fmt.Println("ok")
}
```

I can find my trace with log in the trace page
![image](https://user-images.githubusercontent.com/25590607/142985947-11ebc2df-1395-459e-bc5f-98ba83423919.png)

How can I send logs to the log page?

**Comment by wu-sheng** [comment]
Consider using supported 3rd party collectors, https://skywalking.apache.org/docs/main/latest/en/setup/backend/log-analyzer/#log-files-collector. 

There is no bundled log reporter for now.
