### ISSUE TITLE
Can go2sky support output to kafka/pulsar

### ISSUE THREAD

**Issue by Shoothzj** [SkyAPM/go2sky#150]
Can `go2sky` library output data to kafka/pulsar instead of `:11800`?
If `go2sky` can't, I can work on this under guides

**Comment by wu-sheng** [comment]
I think we can't for now.

**Comment by Shoothzj** [comment]
@wu-sheng Is this feature appropriate or in roadmap? Can I work on this?

**Comment by arugal** [comment]
https://github.com/SkyAPM/go2sky-plugins/tree/master/kafkareporter @Shoothzj  Is this?

**Comment by wu-sheng** [comment]
I think so. Kafka reporter is in the plugin repo.
