### ISSUE TITLE
time out

### ISSUE THREAD

**Issue by liuxinggang** [SkyAPM/go2sky#16]
go2sky-gRPC2019/06/11 17:27:39 register error rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: timed out waiting for server handshake

**Comment by wu-sheng** [comment]
@withlin I think you make the agent works, could you share?

**Comment by withlin** [comment]
hi @liuxinggang ,in my Evn.it is run fine.would you provide a example? which will help me tackle the problem.

**Comment by wu-sheng** [comment]
No update. closing.

**Comment by qxs820624** [comment]
it occurs when server is closed
