### ISSUE TITLE
fetch dynamic configuration error rpc error: code = Unimplemented desc = Method not found: skywalking.v3.ConfigurationDiscoveryService/fetchConfigurations

### ISSUE THREAD

**Issue by jiankunking** [SkyAPM/go2sky#170]
**Describe the bug**
fetch dynamic configuration error rpc error: code = Unimplemented desc = Method not found: skywalking.v3.ConfigurationDiscoveryService/fetchConfigurations

**To Reproduce**
go2sky version:v1.5.0 
skywalking version:8.6

**Additional context**

After accessing according to the document, the service will always print the following errors

```
go2sky-gRPC2022/10/10 14:29:13 fetch dynamic configuration error rpc error: code = Unimplemented desc = Method not found: skywalking.v3.ConfigurationDiscoveryService/fetchConfigurations

go2sky-gRPC2022/10/10 14:29:33 fetch dynamic configuration error rpc error: code = Unimplemented desc = Method not found: skywalking.v3.ConfigurationDiscoveryService/fetchConfigurations

go2sky-gRPC2022/10/10 14:29:53 fetch dynamic configuration error rpc error: code = Unimplemented desc = Method not found: skywalking.v3.ConfigurationDiscoveryService/fetchConfigurations
```

**Comment by wu-sheng** [comment]
This means the backend is too old. This method is not supported by this version of the backend.

**Comment by jiankunking** [comment]
> This means the backend is too old. This method is not supported by this version of the backend.

Skywalking 8.6 Which version of go2sky should we use?

**Comment by wu-sheng** [comment]
Sorry, I can't remember that. We only maintain which versions are supported for the latest OAP server, there is no matrix from the agent perspective.
And the whole OAP 8.x is going to end-of-life, https://skywalking.apache.org/events/deprecate-v8/

**Comment by jiankunking** [comment]
> Sorry, I can't remember that. We only maintain which versions are supported for the latest OAP server, there is no matrix from the agent perspective. And the whole OAP 8.x is going to end-of-life, https://skywalking.apache.org/events/deprecate-v8/

Maybe a table corresponding to the client version and skywalking version should be maintained, or the client releases version and skywalking version should be consistent, similar to the version of elasticsearch client and elasticsearch

**Comment by wu-sheng** [comment]
In the open-source community, the thing only exists if someone is taking responsibility. Right now, no one is doing that. So, there is nothing called `should` or `should not`. 
Don't take an example of other communities to prove, and to be honest, ElasticSearch support is never consistent, many breaking changes are there in different versions.

**Comment by jiankunking** [comment]
use go2sky v1.0.0 for skywalking 8.6 is ok
