### ISSUE TITLE
gRPCReporter can use nanosecond instead of millisecond

### ISSUE THREAD

**Issue by Dark1Forest** [SkyAPM/go2sky#174]
If the call time is less than one millisecond, I will not see the call time
like this
![image](https://user-images.githubusercontent.com/49264473/208104784-6d80e5d3-0d4a-41e4-b348-15929ade7181.png)

**Comment by wu-sheng** [comment]
That is not a thing determined by go2sky. This is a SkyWalking ecosystem-level concept.
If a span is less than 1 ms, you should not use a span to measure its performance. That is pointless. 
Setup a meaningful metric for it if you want some statistic.
