### ISSUE TITLE
Make sampling decision with span tags.

### ISSUE THREAD

**Issue by lemonlinger** [SkyAPM/go2sky#175]
I want to make sampling decision with span tags. For example,  I put `UserID` as a tag into a span, then in my custom sampler, `IsSample` decides to sample  or not with the value of `UserID` tag.

**Describe the solution you'd like**
Probably we have to change the definition of `Sampler interface`, like:
```golang
type Sampler interface {
    IsSampled(span Span) bool
}
```
Besides this, a new method `GetTag(Tag) string` also has to be added into `Span`.

Finally, I can implement a custom sampler like below to sample by UserID:
```golang
func (s CustomeSampler) IsSampled(span Span) bool {
    userID := span.GetTag(userIDTag)
    return IsInWhitelist(userID) 
}
```

**Comment by wu-sheng** [comment]
Sampler usually is used to create segment, rather than doing anything after creation.

**Comment by wu-sheng** [comment]
I can't see how your sampler works.

**Comment by lemonlinger** [comment]
> 

Oh yes, I should not use `Span` as the parameter of `IsSampled`. `SamplingParameters` is probably more sensible which is used in OpenTelemetry. Basically, I need more context to determine a span is sampled or not, rather than just operation name. Let me show you how it works in OpenTelemetry. 
```golang
// Sampler goes like this in OpenTelemetry
type Sampler interface {
    ShouldSample(parameters SamplingParameters) SamplingResult
}

// SamplingParameters contains the values passed to a Sampler.
type SamplingParameters struct {
    ParentContext context.Context
    TraceID       trace.TraceID
    Name          string
    Kind          trace.SpanKind
    Attributes    []attribute.KeyValue  // attribute.KeyValue is like Tag in Skywalking.
    Links         []trace.Link
}

// Infos in SamplingParameters can be constructed from SpanStartOption. 
func (*tracer) Start(ctx context.Context, name string, options ...trace.SpanStartOption) (context.Context, trace.Span)
// Start is used to create a span which is counterpart in OpenTelemetry of CreateLocalSpan/CreateEntrySpan in go2sky.
```
But I found out it's not trivial to implement this in go2sky with minor changes.

**Comment by wu-sheng** [comment]
First, OpenTracing is archived. And there is no bridge between go2sky and ot.
Then SkyWalking is not span oriented, that is not concept.
We can't adopt a thing we don't have.

**Comment by lemonlinger** [comment]
I see. Closed.
