### ISSUE TITLE
How to get the current SegmentContext object inside the program

### ISSUE THREAD

**Issue by treeyh** [SkyAPM/go2sky#25]

**Comment by wu-sheng** [comment]
Why do you need that object inside? It should not.

**Comment by treeyh** [comment]
When the program outputs the running log, I want to be able to bring the TraceId information to facilitate the association.

**Comment by wu-sheng** [comment]
TraceId should be opened in another method. Such as `h.tracer.traceid(Context)`(Haven't today). But the SegmentContext is not the thing should be opened.

You could consider contributing this.

**Comment by arugal** [comment]
I will be contributing.

**Comment by arugal** [comment]
provided
