### ISSUE TITLE
go2sky 到 java

### ISSUE THREAD

**Issue by CrossingTheRiverPeole** [SkyAPM/go2sky#28]
I want to use go2sky to generate the traceID and then call the backend java service so that I can complete the link monitoring.

**Comment by wu-sheng** [comment]
Then? The protocol is compatible. Go2sky is following SkyWalking protocol.

**Comment by CrossingTheRiverPeole** [comment]
The problem is this: my java service uses skywalking for link monitoring, and the front end uses nginx for service forwarding. At this time, nginx cannot be added to link monitoring when forwarding. At this point, I want to use go2sky and then combine the lua script. Can this scheme generate a complete monitoring link?

**Comment by wu-sheng** [comment]
This is a golang agent, nothing related to lua script.
