### ISSUE TITLE
Error while dialing dial tcp: lookup oap-skywalking: Temporary failure in name resolution

### ISSUE THREAD

**Issue by surechen** [SkyAPM/go2sky#29]
**Describe the bug**

go2sky-gRPC2019/09/29 19:19:41 register error rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp: lookup oap-skywalking: Temporary failure in name resolution"

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by wu-sheng** [comment]
This seems simply can't find the oap backend.

**Comment by surechen** [comment]
Can you show how to solve this problem? Is there anything wrong with skywalking when I configure it?

**Comment by surechen** [comment]
Is there something wrong in following logs?
go2sky-gRPC2019/10/08 14:37:43 the id of service 'calculator' is 2
go2sky-gRPC2019/10/08 14:37:43 register error fail to instance service
go2sky-gRPC2019/10/08 14:37:44 the id of instance '21dccf14-e996-11e9-91fe-fa163ef423d3' id is 327

**Comment by wu-sheng** [comment]
There is nothing wrong about the above log.

**Comment by surechen** [comment]
I succeeded in reporting information to skywalking.I would appreciate it if you can show more use cases of complex scenarios. Thanks.

**Comment by wu-sheng** [comment]
> I succeeded in reporting information to skywalking.I would appreciate it if you can show more use cases of complex scenarios. Thanks.

What do you mean more complex scenario? SkyWalking backend is powerful to support very large scale, verified by many Java and .NetCore agent users.
