### ISSUE TITLE
EntrySpan and ExitSpan.

### ISSUE THREAD

**Issue by surechen** [SkyAPM/go2sky#30]
**Describe the bug**
I have three services a, b and c. Interaction between services is user->a->b->c. I use function CreateEntrySpan in a and CreateExitSpan in b. The topology diagram in skywalking is not in line with my expectations which is  user->a and b->c. But there is no line between a and b.
Could  you show me how to solve this problem. Thanks 

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/7249331/66470118-991b5500-eabb-11e9-8feb-ae10e72bbc5d.png)

In this png user -> mersher-webapp(CreateEntrySpan) -> calculator(CreateExitSpan) -> 127.0.0.1:4500.
**Desktop (please complete the following information):**

**Additional context**

**Comment by wu-sheng** [comment]
> I use function CreateEntrySpan in a and CreateExitSpan in b.

I am a little confused about this usage. Entry and exit span creations should be used in every service. Entry span is the HTTP handler's responsibility and exit span represents the outgoing call at client side.

**Comment by surechen** [comment]
Could you show me some example code for using SkyAPM/go2sky in multi-service Interaction scenario?Thanks.

**Comment by wu-sheng** [comment]
When you received a HTTP request, create an entry span(extract the context). Before you call target, create exit span(inject context). And you need to read SkyWalking document and plugin development guide. The basic concepts are all there.
