### ISSUE TITLE
Performance of report.

### ISSUE THREAD

**Issue by surechen** [SkyAPM/go2sky#31]
**Is your feature request related to a problem? Please describe.**
I find that function newSegmentRoot will create a coroutine for every request . At the end of each Segment collection, a message is sent immediately.I'm afraid this will affect performance.

**Describe the solution you'd like**

I'm wondering if go2sky can implement a collector to collect messages and send them based on time and quantity dimensions, so as to avoid creating a large number of coroutines in high concurrency scenarios.User can set report interval and number of segments.

**Describe alternatives you've considered**

**Additional context**

**Comment by wu-sheng** [comment]
Could you point out the codes about this concern?

**Comment by surechen** [comment]
> Could you point out the codes about this concern?

Thanks for your reply.I mean in function call chain CreateEntrySpan->CreateLocalSpan->newSegmentSpan->newSegmentRoot. In func newSegmentRoot :

**Comment by wu-sheng** [comment]
> I'm worried about performance. 

If this reports as a grpc stream, it is safe. SkyWalking javaagent doesn't need any collector, it could work in 5k-10k tps with 10% CPU only. Your concern should base on experiences, and code optimization. In most cases, the collector wouldn't help.

**Comment by surechen** [comment]
> > I'm worried about performance.
> 
> If this reports as a grpc stream, it is safe. SkyWalking javaagent doesn't need any collector, it could work in 5k-10k tps with 10% CPU only. Your concern should base on experiences, and code optimization. In most cases, the collector wouldn't help.

Thansk for your reply.
