### ISSUE TITLE
Can go2sky send traces to SkyWalking Java oap server and make up a complete link with Java agents?

### ISSUE THREAD

**Issue by pmq5205209** [SkyAPM/go2sky#32]
Our company has used the SkyWalking for almost 100 Java applications. And we use Grafana，which connected with some Java applications that deployed with SkyWalking Java Agent.  We want the Grafana be traced with SkyAPM and linked with these Java applications. So, can go2sky send traces to SkyWalking Java oap server and make up a complete link with Java agents?

**Comment by wu-sheng** [comment]
How could you inject go2sky into Grafana?

**Comment by hanahmily** [comment]
Quick answer:YES
go2sky implemented skywalking tracing protocol, that means it can work with
any skywalking agent including Java.

**Comment by pmq5205209** [comment]
Grafana uses Jaeger for tracing. Grafana includes many customized datasources. We have developed our own private datasources. Grafana calls Java middle platform to realize data visualization. Java middle platform uses skywalking for tracing. We want to connect the two, so we want to use go2sky instead of Jaeger.

**Comment by wu-sheng** [comment]
If you want to instrument grafana, try to integrate go2sky into it. Then you have the traces across them.

**Comment by PrettyJerry** [comment]
Wonderful！
Grafana is the most popular data visualization tool. If go2sky can successfully connect Grafana and Java microservices,  it is of great significance. It means  the successful integration of Skywalking in Go and Java.
