### ISSUE TITLE
Can't query any tracing data from the skywalking-ui

### ISSUE THREAD

**Issue by 18981119465** [SkyAPM/go2sky#33]
I created a go2sky-example and verified its functionality, the results are:
- service registry: ok
- service query: ok
- topology graph: ok
- **tracing: failed (no data could be queried)**
What did i do wrong? or is there any bug in go2sky http plugin?
go2sky-example git repository is [https://github.com/18981119465/go2sky-example](url)

**Comment by wu-sheng** [comment]
Topology is based on trace. So basically, they are the same thing. You need to invest, the indes has data.

**Comment by 18981119465** [comment]
> Topology is based on trace. So basically, they are the same thing. You need to invest, the indes has data.

Now, it works fine. but i don't know why. I try to find out some patterns, but i can't reprocude the problem now. >_<
