### ISSUE TITLE
Agent will try to register service and instance  until succeed. It will block the thread.

### ISSUE THREAD

**Issue by pmq5205209** [SkyAPM/go2sky#34]
I make agent to register service and instance in main thread. If the backend service of the collector is invalid, the thread will be blocked.

**Comment by wu-sheng** [comment]
If you don't, you need more mechanisms to accept the context is not available, like Java or other agents did. Please consider to send a pull request.

**Comment by wu-sheng** [comment]
Register is gone since the v3 trace format. Closing.
