### ISSUE TITLE
gin.Middleware initializes routeMap by gin.Context

### ISSUE THREAD

**Issue by xuzq3** [SkyAPM/go2sky#51]
gin.Middleware has a bug to initialize routeMap by gin.Context and the operationName will be wrong for the next request.

**Comment by wu-sheng** [comment]
Which library has a bug? go2sky or 3rd party?

**Comment by xuzq3** [comment]
> Which library has a bug? go2sky or 3rd party?

go2sky/plugins/gin/gin.go

**Comment by wu-sheng** [comment]
Could you try to submit a pull request to fix it?

**Comment by arugal** [comment]
Hi @xuzq3  can you provide your code, I can't reproduce this bug :)

**Comment by xuzq3** [comment]
go2sky/plugins/gin/gin.go
```
m.routeMapOnce.Do(func() {
	routes := engine.Routes()
	rm := make(map[string]map[string]routeInfo)
	for _, r := range routes {
		mm := rm[r.Method]
		if mm == nil {
			mm = make(map[string]routeInfo)
			rm[r.Method] = mm
		}
		mm[r.Handler] = routeInfo{
			operationName: c.Request.Host + c.Request.URL.Path,same
		}
		m.routeMap = rm
	}
})
```
Because of sync.Once, routeMap is initialized by gin.Context of the first request. And it will never change. When the url of the next request is different, operationName is wrong.

**Comment by arugal** [comment]
haha @xuzq3  are you interested in fixing it :)
