### ISSUE TITLE
Please do not delete releases or tags

### ISSUE THREAD

**Issue by cch123** [SkyAPM/go2sky#57]
**Describe the bug**
When user depends on your library, they may not vendor it. If a tag or a release was removed, then go build will fail.

**To Reproduce**
go.mod:
```go
module whatever.com/ccc

go 1.12

require (
        github.com/SkyAPM/go2sky v0.3.1-0.20200329092408-8b3e4d536d8d
)
```

**Expected behavior**
go build success

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by wu-sheng** [comment]
0.3.1? @arugal When did we release this?

**Comment by wu-sheng** [comment]
@arugal I received DM from MOSN community too, seems you used the wrong tag somehow? The `0.3.0-mosn` should be tag name. Could you fix this on our repo and MOSN repo ASAP?

**Comment by arugal** [comment]
Hi @cch123 

Thank you for your feedback. Do you mean that if I delete the branch or tag of go2sky, it will cause potential problems?

**Comment by cch123** [comment]
@arugal , yes~

**Comment by arugal** [comment]
@cch123 golang solution should be [vendor](https://go.googlesource.com/proposal/+/master/design/25719-go15vendor.md), [mosn](https://github.com/mosn/mosn/tree/master/vendor/github.com/SkyAPM/go2sky) does the same thing.

 Please let me know if I'm wrong :)

@wu-sheng release a new tag won't solve it. Anyway, I will finish it as soon as possible.

**Comment by cch123** [comment]
After investigation, this is a goproxy cache issue, sorry for misunderstanding...

**Comment by wu-sheng** [comment]
Thank you all for quick clarification.
