### ISSUE TITLE
gin plugin bugfixed in master, but it still exists in v0.3.0, release a new version?

### ISSUE THREAD

**Issue by Logic0** [SkyAPM/go2sky#58]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
using this still import the version with bug:
`import "github.com/SkyAPM/go2sky/plugins/gin"`

found the bug was fixed 2 months ago, the code(in plugin/gin.go):
from `operationName: c.Request.Host + c.Request.URL.Path,` to `operationName: fmt.Sprintf("/%s%s", r.Method, r.Path),`

release a new version?

**Describe alternatives you've considered**

**Additional context**

**Comment by wu-sheng** [comment]
The new release will follow the main repo 8.0.0 release, because v3 protocol is required.
