### ISSUE TITLE
routeMap key is handler name, if different url paths route to same handler, only the last one is available to trace, consider using Method+Path as the key?

### ISSUE THREAD

**Issue by Logic0** [SkyAPM/go2sky#59]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

routeMap key is handler name, if different url paths route to same handler, only the last one is available to trace, consider using Path as the key to solve this? or any other solutions?

`mm[r.Handler] = routeInfo{
                    operationName: fmt.Sprintf("/%s%s", r.Method, r.Path),
                }`

described situation can be avoided by using different handlers for different urls, but it takes time to find why when it happens.

**Additional context**

**Comment by arugal** [comment]
Hi @Logic0 
Glad to receive your feedback. I don't quite understand what you said. Could you give me an example :)

**Comment by Logic0** [comment]
if we have a handler like:
`func doSomething( c *gin.Context ) {...}`

then register 2 handler:
```
eg = gin.New()
eg.Use( Middleware(eg, tracer) )
eg.POST( "/api/v1/m1", doSomething )
eg.POST( "/api/v1/m2", doSomething )
```
according to the code in go2sky gin plugin:
`mm[r.Handler] = routeInfo{ operationName: fmt.Sprintf("/%s%s", r.Method, r.Path), }`

the **mm** will be:
```
mm['doSomething'] = "/POST/api/v1/m1"         // will be overwrited by m2
mm['doSomething'] = "/POST/api/v1/m2"
```

hope this helps.

**Comment by arugal** [comment]
Thank you. It does happen. Let me see how to solve it.

**Comment by arugal** [comment]
Hi @Logic0, If use `http.request.Method + http.request.URL.path` as the operation name, so `/user/:name` will generate multiple operation names, I will keep the current solution until there is a better solution.

**Comment by wu-sheng** [comment]
We added the logic endpoint concept in the next 8.1 release. https://github.com/apache/skywalking/pull/4985
I am feeling it matches this? The core point of the operation name should be metrics only, right?

**Comment by wu-sheng** [comment]
We did a discussion, this should be plugin FAQ.

**Comment by wu-sheng** [comment]
@Logic0 As you have known the logic behind this, I recommend using a method wrapper to make this conflict gone. I have talked with @arugal, my suggestion would like to add a FAQ document with an example.

**Comment by arugal** [comment]
Hi @Logic0 https://github.com/SkyAPM/go2sky-plugins/tree/master/gin/v3 We provide a new version, welcome to use.
