### ISSUE TITLE
hope reporter support logger interface{}

### ISSUE THREAD

**Issue by cclehui** [SkyAPM/go2sky#66]
**Is your feature request related to a problem? Please describe.**
our application use self defined logger module , which is not log.Logger  .  but implements level logger interface{} .

but the reporter.grpc.WithLogger(logger *log.Logger)   only support  *log.Logger 

type LevelLogger interface {
    Debug(msg string)
    Debugf(format string, v ...interface{})
    Info(msg string)
    Infof(format string, v ...interface{})
    Warn(msg string)
    Warnf(format string, v ...interface{})
    Error(msg string)
    Errorf(format string, v ...interface{})
}

**Describe the solution you'd like**
define a logger interface , so we can overwrite

**Comment by wu-sheng** [comment]
I don't think we should define a duplicated logger interface. Especially, golang has one already.
