### ISSUE TITLE
go2sky conflict with etcdv3

### ISSUE THREAD

**Issue by lchb369** [SkyAPM/go2sky#69]
import (
	"context"
	"github.com/SkyAPM/go2sky"
	"github.com/SkyAPM/go2sky/reporter"
	_ "github.com/coreos/etcd/clientv3"
	"github.com/robfig/cron"
	"log"
	"time"
)

report error:

GOROOT=C:\Go #gosetup
GOPATH=D:\gopath #gosetup
C:\Go\bin\go.exe build -o C:\Users\admin\AppData\Local\Temp\___go_build_main_go__1_.exe -gcflags "all=-N -l" D:\projects\go-micro-demo\micro\crontab-service\main.go #gosetup
# github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
D:\gopath\pkg\mod\github.com\coreos\etcd@v3.3.18+incompatible\clientv3\balancer\resolver\endpoint\endpoint.go:114:78: undefined: resolver.BuildOption
D:\gopath\pkg\mod\github.com\coreos\etcd@v3.3.18+incompatible\clientv3\balancer\resolver\endpoint\endpoint.go:182:31: undefined: resolver.ResolveNowOption
# github.com/coreos/etcd/clientv3/balancer/picker
D:\gopath\pkg\mod\github.com\coreos\etcd@v3.3.18+incompatible\clientv3\balancer\picker\err.go:37:44: undefined: balancer.PickOptions
D:\gopath\pkg\mod\github.com\coreos\etcd@v3.3.18+incompatible\clientv3\balancer\picker\roundrobin_balanced.go:55:54: undefined: balancer.PickOptions

Compilation finished with exit code 2

**Comment by wu-sheng** [comment]
@arugal Do we have dependency about etcd? I am confused.

**Comment by arugal** [comment]
Hi @lchb369,  It seems that your situation is the same with this [issue](https://github.com/SkyAPM/go2sky/issues/67), do you use `go-micro` ？

**Comment by arugal** [comment]
> @arugal Do we have dependency about etcd? I am confused.

`go2sky` only dependencies related to `grpc`.

**Comment by jiawei8** [comment]
gRPC v1.27 is not compatible with etcd v3.3.18,you can upgrade etcd version to v3.4,see this [issue](https://github.com/etcd-io/etcd/issues/11931)

**Comment by lchb369** [comment]
//解决etcdv3与grpc冲突问题https://www.jianshu.com/p/1971a27096b9
replace google.golang.org/grpc => google.golang.org/grpc v1.26.0

**Comment by lchb369** [comment]
@arugal  yes,I am use go-micro

**Comment by arugal** [comment]
@lchb369 The cause has been found. Closed.
