### ISSUE TITLE
how to set client sample rate 

### ISSUE THREAD

**Issue by bufferflies** [SkyAPM/go2sky#70]
I read the trace.go code ,I find the sample set 1。 
![image](https://user-images.githubusercontent.com/23159587/89705936-045fdd00-d994-11ea-8b9f-4b96776ecfc0.png)

**Comment by arugal** [comment]
@bufferflies  now go2sky also supports sampling, and contributions are welcome.

**Comment by xbkaishui** [comment]
Please assign to me, thx

**Comment by xbkaishui** [comment]
@bufferflies Client sample feature is merged, you can try it and let me know
