### ISSUE TITLE
Is v0.5.0 not backward compatible?

### ISSUE THREAD

**Issue by bejens** [SkyAPM/go2sky#71]
**Describe the bug**

When I use go2sky@v0.5.0 client to conection skywalking@6.6.0 server. I got this error:
**report serviceInstance properties error rpc error: code = Unimplemented desc = Method not found ManagementService/reportInstanceProperties.**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - go2sky client version: v0.5.0
 - skywalking server version: 6.6.0

**Additional context**

**Comment by arugal** [comment]
Yes,  [v3 protocols](https://github.com/apache/skywalking/blob/master/docs/en/protocols/README.md) has been used since 0.4.0, you can try version before 0.3.0.

**Comment by bejens** [comment]
But when I use 'go get -u'  to get code,This repository will upgrade.  How can I lock repository version in go.

**Comment by arugal** [comment]
> But when I use 'go get -u' to get code,This repository will upgrade. How can I lock repository version in go.

You can specify the version in `go.mod`.
