### ISSUE TITLE
Support database query tracing using ocsql library 

### ISSUE THREAD

**Issue by Saicasm** [SkyAPM/go2sky#78]
**Is your feature request related to a problem? Please describe.**
Currently go2sky doesn't automatically trace the database queries and its execution

**Describe the solution you'd like**
A wrapper which automatically traces the database query execution and produces the trace and links it to the parent span which can be a Http method/ any other 

**Additional context**
[ocsql warpper](https://github.com/opencensus-integrations/ocsql) which provides tracing for tracing applications like zipkin and since skywalking uses different data format some code changes to the library will be required

**Comment by arugal** [comment]
Looks good, @Saicasm Do you plan to contribute this plugin?

**Comment by Saicasm** [comment]
> Looks good, @Saicasm Do you plan to contribute this plugin?

@arugal  definitely would be contributing, are there any links or any examples in other languages for reference  .If I can have some context that would be great, Thank you

**Comment by arugal** [comment]
> are there any links or any examples in other languages for reference?

About of database, as this [comment](https://github.com/SkyAPM/go2sky/issues/77#issuecomment-730449624) says, you can also refer to our other plugin implementations, such as [go-restful](https://github.com/SkyAPM/go2sky-plugins/blob/master/go-restful/go_restful.go).

**Comment by Saicasm** [comment]
Hi @arugal , is there a reference where i can find the component ID for go plugins ?
Currently need the componentID for mysql ,sqlLite ,postgres.

Thank you

**Comment by arugal** [comment]
> Hi @arugal , is there a reference where i can find the component ID for go plugins ?
> Currently need the componentID for mysql ,sqlLite ,postgres.
> 
> Thank you

It need to be defined in [component-library.yml](https://github.com/apache/skywalking/blob/master/oap-server/server-bootstrap/src/main/resources/component-libraries.yml), refer to `PyMysql`.

https://github.com/apache/skywalking/blob/master/oap-server/server-bootstrap/src/main/resources/component-libraries.yml#L47
https://github.com/apache/skywalking/blob/master/oap-server/server-bootstrap/src/main/resources/component-libraries.yml#L464
https://github.com/apache/skywalking/blob/master/oap-server/server-bootstrap/src/main/resources/component-libraries.yml#L548

**Comment by wu-sheng** [comment]
If those are planned to be supported in golang, please submit a pull request to update the `languages` part.

**Comment by Saicasm** [comment]
@arugal the plugin dev is almost done the issue i'm facing is if there's a db call without context then the parent span is not linked ,so my question is if i can store the context of each request ?so that every exitSpan is linked to parent span.
