### ISSUE TITLE
How to get the size and capacity send queue ?

### ISSUE THREAD

**Issue by eyjian** [SkyAPM/go2sky#79]
场景：
动态调整上报采样率，在低上报时全采样，随着队列大小增加降低采样率。对于GRPCReporter可如下实现，LogReporter没有对应的实现。

`
// GetSendQueueSize return the size of send queue and the capacity of send queue
func GetSendQueueSize(reporter interface{}) (int, int) {

	r, ok := (reporter).(gRPCReporter)
	if !ok {
		return -1, -1
	} else {
		return len(r.sendCh), cap(r.sendCh)
	}
}
`

**Comment by arugal** [comment]
Hi @eyjian, 看起来不错，可以增加一种新的 [Sampler](https://github.com/SkyAPM/go2sky/blob/master/sampler.go#L25) 实现，你有兴趣实现吗?
