### ISSUE TITLE
Make span tag key/value pairs to be utf-8 encoded

### ISSUE THREAD

**Issue by buxingzhe** [SkyAPM/go2sky#82]
**Is your feature request related to a problem? Please describe.**
Our application shows the log like below due to the URL path contain non utf-8 encoded characters.
 "go2sky-gRPC2020/12/28 18:49:46 send segment error rpc error: code = Internal desc = grpc: error while marshaling: proto: field "KeyStringValuePair.Value" contains invalid UTF-8"
**Describe the solution you'd like**
 The sdk should always encode the key/value string for tags with utf-8. 

**Describe alternatives you've considered**

**Additional context**

**Comment by wu-sheng** [comment]
> the URL path contain non utf-8 encoded characters.

Why is that? If it is URL encoded, it should have UTF-8 encoded already.

**Comment by buxingzhe** [comment]
As the log doesn't output the real string value, so I'm not sure why this happened.
I think it's probably related to the setting of "span.Tag(go2sky.TagURL, req.URL.String()). As the URL may have query parameters that contain characters like Chinese.

**Comment by wu-sheng** [comment]
URL includes parameters? Which framework having this feature? URL should be encoded even for Chinese.

**Comment by buxingzhe** [comment]
Here is a URL that with query parameters. Query parameters are the key value pairs after '?'.
https://www.baidu.com/s?wd=中文&rsv_spt=1&rsv_iqid=0xee4f0d5400029778

**Comment by wu-sheng** [comment]
OK, we should use `uri#encoding` before put it into the tags.

**Comment by arugal** [comment]
![image](https://user-images.githubusercontent.com/26432832/109170801-154f2f00-77bc-11eb-9dd2-c6feeb21236f.png)
Hi @buxingzhe Can you give me more information? I didn't come across `proto: field "KeyStringValuePair.Value" contains invalid UTF-8` :)

**Comment by buxingzhe** [comment]
I just found such errors in our log, but I don't figure out how it happens.
Here are some links related to this issue, hope to help you.
https://github.com/golang/protobuf/issues/1228
https://stackoverflow.com/questions/15139449/google-protocol-buffer-error-encountered-string-containing-invalid-utf-8-data
