### ISSUE TITLE
Provide cross-thread transfer and expand information field function

### ISSUE THREAD

**Issue by xuguoqi302** [SkyAPM/go2sky#88]
**Describe the solution you want**
Provides cross-thread link transfer extended information field

**Describe the alternatives you considered**
Similar function to Java agent:
TraceContext.putCorrelation("test-flow", testFlag);
Optional<String> testFlowOpt = TraceContext.getCorrelation("test-flow");
Similar functions can be obtained from go2sky sdk to facilitate the transmission of field information links

**Other content**

**Comment by wu-sheng** [comment]
Contributions are welcome.
