### ISSUE TITLE
Get Span from ctx

### ISSUE THREAD

**Issue by matianjun1** [SkyAPM/go2sky#96]
Sometime I need spanFromContext

such as [go-redis-hook](https://github.com/go-redis/redis/blob/55db07d5d106172e712d815ad3185084a1c61f5c/redis.go#L25)

```
type Hook interface {
	BeforeProcess(ctx context.Context, cmd Cmder) (context.Context, error)
	AfterProcess(ctx context.Context, cmd Cmder) error
}
```

only ctx can be propagation, I cant do span.End further

Maybe there is a easy way to solve, set ctxKeyInstance to be public. Then I can use this key to get activeSpan from ctx and do (.Span) to get a Span

**Comment by wu-sheng** [comment]
Typically, this should be called `ctx#activeSpan`. We are welcome the contribution.
