### ISSUE TITLE
How to trace MQTT

### ISSUE THREAD

**Issue by kehuili** [SkyAPM/go2sky#99]
In examples, we need to pass request context to extract or inject information, however, there's no such thing in MQTT when publish or subscribe messages. 
I would like to know if there is a way to trace MQTT, thanks.

**Comment by wu-sheng** [comment]
I am not sure what do you mean no such thing. Header or so-called metadata exist in queue, including Kafka, RocketMQ, ActiveMQ, etc. It is a common concept, and there are various queue-based instrumentation in different language agents.
